### ISSUE TITLE
LambdaSim deployment

### ISSUE THREAD

**Issue by vhaxha** [mbonvini/LambdaSim#3]
Hi Marco,

How are you?
Thank you very much for deployment this great application (LambdaSim).
I would like to ask you:
       1. did you use S3 Bucket and Cognito.
       2. As AWS changes to new version, do you update your  code.
I was trying to replicate your LambdaSim example as a test on Amazon, but unsuccessful.

Please, let me know if you have user guide or the deployment guide.

Kind regards,
Vesel

**Comment by mbonvini** [comment]
Hi Vasel and thanks!

1. Yes S3 buckets are part of what's needed to deploy an app.
No, cognito is not required unless you want to limit access to the app (I've not tried this yet)
2. I guess that if the image used by AWS for running the application changes drastically then I have to rebuild the core of the Python environment with all its dependencies.

What exactly went wrong when you tried to create your app?

-Marco

**Comment by vhaxha** [comment]
Hi Marco,

Thank you for your quick reply.
I have Atom editor (https://atom.io/) in windows 10 operating system.
Usually in Atom editor powershell I use this command to deploy the application: **serverless deploy -v**.
In this case are you using aws Linux virtual machines  (where the web application is deployed?).

Kind regards,
Vesel

**Comment by mbonvini** [comment]
You should read this article I wrote
https://marcobonvini.com/modelica/2017/03/26/model-as-a-service.html

The application is deployed on AWS in a Lambda function and some resources are
stored in S3.

You should give a look at the instruction in the [wiki](https://github.com/mbonvini/LambdaSim/wiki), they describe how to actually use LambdaSim.

**Comment by vhaxha** [comment]
Thank you very much for pointing me I right direction.
